### ISSUE TITLE
<exclude/include>not working

### ISSUE THREAD

**Issue by katerinawang** [Jamling/hexo-generator-index2#1]
once i tried to load exclude/include, it did not generate index.html in public folder.
idk if it's because hexo 3.2 released and it has the same exclude/include features.
maybe you could change the name of these two?

**Comment by Jamling** [comment]
Have you installed the hexo-generator-index2 to replace the origin hexo-generator-index plugin?

**Comment by katerinawang** [comment]
yes i followed the instructions exactly on your github.
i have found an alternative way to exclude the categories on index page.
but need to change some code manually.

**Comment by Jamling** [comment]
~It works well for my blog (hexo ver 3.2). You can send me your _config.yml and package.json to duplicate it.

**Comment by katerinawang** [comment]
thanks a lot!
here is the repo of the files.
[github link](https://github.com/kagomemiao/files)

**Comment by Jamling** [comment]
It's seems no problems in your config. I try to exclude the category/tag of my blog with this plugin, it works well for me. :(

**Comment by katerinawang** [comment]
no worries, thank you anyway.
