### ISSUE TITLE
还需修改站点概览中文章总数

### ISSUE THREAD

**Issue by lancelot-lewis** [Jamling/hexo-generator-index2#5]
配置完隐藏部分文章之后，站点概览信息的数字还是所有文章总数，不能做到对应的减少

**Comment by Jamling** [comment]
可以具体一点吗？或者截个图给我。

**Comment by lancelot-lewis** [comment]
@Jamling 比如在首页下，我隐藏了两个文件（总数16），应该显示为14，但结果还是16，如下图
![image](https://user-images.githubusercontent.com/8749615/42213117-8c5f2afa-7eea-11e8-9c3e-c1f69ab78e85.png)
其实倒不是你插件写的不够好，是 hexo 本身的问题。这两天在研究 hexo 插件的写法，找到一个 hack 方式，先贴图
![image](https://user-images.githubusercontent.com/8749615/42213321-02ce9266-7eeb-11e8-852b-f0fccc1700e8.png)
可以在 92-93 行之间添加一句`locals.posts = posts`，就能实现文章总数减成对应数字

**Comment by Jamling** [comment]
日志数，是所有博客的总数吧？日志数＝分类数+标签数？hexo-generator-index2是指定界面的生成插件。它不会更改hexo-generator-tag等其它插件的工作。locals.posts = ports 会不会将过滤后的posts作为全站的posts？如果是的话，这可不能随便改，一改就会影响到其它生成插件。
如果你想在全站范围内隐藏文章，应该是将文章的源文件(xx.md)从_posts移到_draft 目录

**Comment by lancelot-lewis** [comment]
@Jamling 不能修改的原因我懂，但是我试过，在我自己本地没看到有影响其他插件的工作。另外这个 _draft  目录内的文章无法通过地址访问，所以还是不能满足我的需求。
```
日志数，是所有博客的总数吧？ 对
日志数＝分类数+标签数？ 错（我这边是刚好加起来16，巧合巧合）
```
我自己想实现的一个插件是通过页面内的 front-matter 来设置一个`hide`字段来控制页面是否在各个列表中显示，尝试了很久都没找到正确的插件写法，不知道你对这个想法有没有什么建议？

**Comment by Jamling** [comment]
- 1，_draft：嗯，是的，_draft表示是草稿，不会发布（生成），所以无法访问。
- 2，日志数，你添加`locals.posts = ports`后，日志数会变成14吗？关于日志数，应该是你主题的功能。
- 3，front-matter，很简单，front-matter中的变量，都可以通过page来获取。取到之后，自己参考处理。
- 4，hide，应该无法做到隐藏，因为插件只能控制生成，生成，则都能访问，不生成，访问不了。如果你不想别人看到你的内容，可以通过加密来实现。hexo有加密插件，我编写的主题hexo-theme-nova也是支持加密的。http://www.ieclipse.cn/other/password.html 
- 5，综上，我的建议是你使用加密插件或加密主题。

**Comment by lancelot-lewis** [comment]
所以还是没办法从插件层面去解决这个问题。
回答2：会变的，我试了很多遍，也自己写了一个插件尝试，都是有效的。
我是用了一个加密插件的，顺便还想从列表中隐藏，比较贪心，哈哈。
谢谢你啦~
