### ISSUE TITLE
请问如何将多个目录都设为index布局呢？

### ISSUE THREAD

**Issue by moegay** [Jamling/hexo-generator-index2#8]
例如，在_posts目录下，有A和B两个目录，请问如何处理才能达到下面这个效果呢： 
网站根目录为 / ，首页只显示 path: A，排除 path: B；
而B目录我选择通过navbar上的menu跳转过去，同时其layout也采用index。
  
问题出在这里： 我尝试在config中设置两个 layout: index ，但是generate之后只生成了目录A
（之所以想搞多个index是因为不想用categories）

**Comment by moegay** [comment]
问题已解决🤣
我把B目录下的文章时间设置得太远了，所以没法生成。问题与index2无关

**Comment by Jamling** [comment]
👍
